"use client";
import { Suspense,useEffect,useState,type FormEvent } from "react";
import { useParams,useSearchParams } from "next/navigation";
import Link from "next/link";
import { configured,supabase,errorMessage } from "@/lib/supabase";
type Business={id:string;name:string;slug:string;category:string|null;address:string|null};type Program={id:string;reward_name:string;required_visits:number};
function JoinContent(){
 const {slug}=useParams<{slug:string}>();const card=useSearchParams().get("card");const [business,setBusiness]=useState<Business|null>(null);const [program,setProgram]=useState<Program|null>(null);const [name,setName]=useState("");const [email,setEmail]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!configured){setLoading(false);return;}const run=async()=>{const client=supabase();const {data:b,error}=await client.from("businesses").select("id,name,slug,category,address").eq("slug",slug).maybeSingle();if(error||!b){setMessage("Commerce introuvable.");setLoading(false);return;}setBusiness(b);const {data:p}=await client.from("programs").select("id,reward_name,required_visits").eq("business_id",b.id).eq("active",true).maybeSingle();setProgram(p);const {data:{user}}=await client.auth.getUser();if(user){const {data:c}=await client.from("customers").select("id").eq("auth_user_id",user.id).maybeSingle();if(c&&p){const {data:m}=await client.from("memberships").select("id").eq("customer_id",c.id).eq("program_id",p.id).maybeSingle();if(m){if(card){await client.rpc("claim_card",{p_token:card,p_membership:m.id});}location.replace(`/customer?membership=${m.id}`);return;}}setEmail(user.email||"");setName(user.user_metadata?.display_name||"");}setLoading(false);};void run();},[slug,card]);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!program)return;setBusy(true);setMessage("");try{const client=supabase();const {data:{user}}=await client.auth.getUser();if(!user){const next=`/join/${encodeURIComponent(slug)}${card?`?card=${encodeURIComponent(card)}`:""}`;const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/auth/callback?next=${encodeURIComponent(next)}`,data:{display_name:name.trim()},shouldCreateUser:true}});if(error)throw error;setMessage("Un lien de connexion vient d’être envoyé. Ouvrez-le depuis cet appareil pour créer ou retrouver votre carte.");return;}
 const {data:existing,error:readError}=await client.from("customers").select("id").eq("auth_user_id",user.id).maybeSingle();if(readError)throw readError;
 let customerId=existing?.id;if(!customerId){const {data:created,error}=await client.from("customers").insert({auth_user_id:user.id,display_name:name.trim()}).select("id").single();if(error)throw error;customerId=created.id;}
 let {data:membership,error:membershipError}=await client.from("memberships").select("id").eq("customer_id",customerId).eq("program_id",program.id).maybeSingle();if(membershipError)throw membershipError;
 if(!membership){const created=await client.from("memberships").insert({customer_id:customerId,program_id:program.id}).select("id").single();if(created.error)throw created.error;membership=created.data;}
 if(card){const {error}=await client.rpc("claim_card",{p_token:card,p_membership:membership.id});if(error)throw error;}
 location.assign(`/customer?membership=${membership.id}`);
 }catch(error){setMessage(errorMessage(error));}finally{setBusy(false);}};
 return <div className="join-bg"><div className="container join-layout"><div className="join-intro"><span className="kicker">PROGRAMME DE FIDÉLITÉ</span><div className="join-logo">✳</div><h1>{business?.name|| (loading?"Chargement…":"Commerce")}</h1><p>{business?.category} {business?.address&&`· ${business.address}`}</p><div className="join-promise"><span>✳</span><div><strong>Vos visites comptent.</strong><br/>{program?`${program.required_visits} visites pour : ${program.reward_name}`:"Un programme simple à retrouver par email."}</div></div></div><div className="join-panel"><span className="kicker">VOTRE CARTE DIGITALE</span><h2>On se retrouve<br/><em>plus souvent ?</em></h2><p>Accédez à votre carte sans mot de passe grâce à un lien envoyé par email.</p>{!configured?<p role="alert">Supabase n’est pas configuré. Ce parcours ne peut pas inscrire de clients.</p>:<form onSubmit={submit}><label htmlFor="name">Votre prénom</label><input id="name" required maxLength={60} value={name} onChange={e=>setName(e.target.value)} autoComplete="given-name"/><label htmlFor="email">Votre email</label><input id="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/><p className="form-note">Votre email sert à retrouver votre carte. Les communications commerciales nécessitent un accord distinct.</p><label className="privacy-check"><input type="checkbox" required/> J’ai lu les informations sur l’utilisation de mes données pour gérer la carte de fidélité.</label><button className="button dark full" disabled={busy||!program}>Continuer →</button></form>}{message&&<p role="status">{message}</p>}<p className="form-note">En continuant, vous acceptez l’utilisation de ces données pour gérer votre carte. <Link href="/privacy">Voir la confidentialité</Link>.</p></div></div></div>;
}

export default function JoinClient(){return <Suspense fallback={<div className="container page">Chargement…</div>}><JoinContent/></Suspense>;}
