import Link from "next/link";
import { LandingCalculator } from "@/components/landing-calculator";
import { LandingPricing } from "@/components/landing-pricing";
import { landingConfig, landingFeatures } from "@/lib/landing-config";

const button = "landing-solid-link inline-flex min-h-12 items-center justify-center rounded-full bg-[#0F2A5F] px-7 text-sm font-bold text-white transition-transform hover:-translate-y-1 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white";
const contrastButton = "landing-outline-link inline-flex min-h-12 items-center justify-center rounded-full border-2 border-white px-7 text-sm font-bold transition-colors hover:bg-white hover:text-[#0F2A5F]";
function Eyebrow({ children }: { children: React.ReactNode }) { return <span className="landing-eyebrow">{children}</span>; }
function SectionHeading({ eyebrow, children, description }: { eyebrow: string; children: React.ReactNode; description?: string }) { return <div className="mb-10 max-w-4xl sm:mb-14"><Eyebrow>{eyebrow}</Eyebrow><h2 className="landing-title mt-5">{children}</h2>{description && <p className="mt-5 max-w-2xl text-base leading-relaxed text-black/65 sm:text-lg">{description}</p>}</div>; }

function FloatingPreview() { return <div className="relative mx-auto h-[430px] max-w-[510px] sm:h-[510px]" aria-label="Aperçu illustratif d’une carte de fidélité et d’un tableau de bord">
  <div className="absolute left-[5%] top-[7%] h-[340px] w-[340px] rounded-full border border-white/45 sm:h-[445px] sm:w-[445px]" aria-hidden/>
  <div className="landing-float-slow absolute left-[2%] top-[8%] z-20 w-[75%] rotate-[-9deg] rounded-[1.5rem] border-2 border-[#0F2A5F] bg-[#F8FAFC] p-5 shadow-[11px_13px_0_#0F2A5F] sm:left-[5%] sm:top-[10%] sm:w-[72%] sm:p-7">
    <div className="flex items-center justify-between text-[10px] font-extrabold uppercase tracking-widest text-[#0F2A5F]/65"><span>Fideli · carte client</span><span className="text-xl text-[#2563EB]">✳</span></div>
    <div className="mt-8 font-display text-3xl uppercase leading-none text-[#0F2A5F] sm:text-4xl">LE CAFÉ<br/>DU COIN</div><p className="mt-2 text-xs text-black/55">Chaque passage compte.</p>
    <div className="mt-7 grid grid-cols-4 gap-2 sm:gap-3">{Array.from({length:landingConfig.programExample.rewardPoints / landingConfig.programExample.pointsPerVisit},(_,index)=><div key={index} className={`grid aspect-square place-items-center rounded-full border-2 text-xs font-bold sm:text-base ${index<landingConfig.mockupExample.cardPoints / landingConfig.programExample.pointsPerVisit?"border-[#0F2A5F] bg-[#2563EB] text-white":"border-dashed border-[#0F2A5F]/30 text-black/25"}`}>{index<landingConfig.mockupExample.cardPoints / landingConfig.programExample.pointsPerVisit?"✳":index+1}</div>)}</div>
    <div className="mt-7 flex justify-between border-t border-black/15 pt-4 text-[10px] font-extrabold uppercase tracking-wider sm:text-xs"><span>{landingConfig.mockupExample.cardPoints} / {landingConfig.programExample.rewardPoints} points</span><span>Encore {landingConfig.programExample.rewardPoints - landingConfig.mockupExample.cardPoints} points ↗</span></div>
  </div>
  <div className="landing-float-fast absolute bottom-[8%] right-[1%] z-30 w-[64%] rotate-[7deg] rounded-[1.4rem] border-2 border-[#0F2A5F] bg-white p-4 shadow-[9px_10px_0_#0F2A5F] sm:bottom-[6%] sm:right-[2%] sm:w-[61%] sm:p-6">
    <div className="flex items-center justify-between"><span className="text-[10px] font-extrabold uppercase tracking-widest text-black/50">Vue commerçant</span><span className="rounded-full bg-[#e5f4dd] px-2 py-1 text-[9px] font-bold text-[#316640]">● En direct</span></div>
    <div className="mt-4 flex items-end gap-2"><strong className="font-display text-5xl leading-none sm:text-6xl">{landingConfig.mockupExample.visitsThisMonth}</strong><span className="pb-1 text-xs text-black/60">visites ce mois-ci<br/>exemple illustratif</span></div>
    <div className="mt-5 flex h-14 items-end gap-2 border-b border-black/15 pb-1" aria-hidden>{[25,42,35,60,45,78,56,88,72].map((height,index)=><span key={index} className="flex-1 rounded-t bg-[#2563EB]" style={{height:`${height}%`}}/>)}</div>
  </div><div className="landing-float-fast absolute right-[1%] top-[2%] z-40 rotate-[8deg] rounded-full border-2 border-[#0F2A5F] bg-[#F59E0B] px-4 py-2 text-xs font-extrabold shadow-[4px_4px_0_#0F2A5F] sm:right-[4%]">SANS APPLI ✦</div>
</div>; }

export default function Home() { const { pointsPerVisit, rewardPoints } = landingConfig.programExample; return <div className="landing-page overflow-hidden bg-[#F8FAFC] text-[#0F2A5F]">
  <section id="accueil" className="relative bg-[#2563EB] text-white"><div className="landing-dots pointer-events-none absolute inset-0 opacity-30" aria-hidden/>
    <nav className="landing-container relative z-50 flex min-h-[78px] items-center justify-between gap-4 border-b border-white/25" aria-label="Navigation de la page d’accueil"><Link href="#accueil" className="font-display text-3xl uppercase tracking-wide" aria-label="Fideli, retour en haut">FIDELI<span className="text-[#0F2A5F]">✳</span></Link><div className="hidden items-center lg:flex">{[["Pourquoi","pourquoi"],["Calculateur","calculateur"],["Fonctionnalités","fonctionnalites"],["Tarifs","tarifs"]].map(([label,id])=><a key={id} className="rounded-full px-5 py-3 text-sm font-bold transition-colors hover:bg-white/15" href={`#${id}`}>{label}</a>)}</div><Link href="/business/login" className="landing-nav-cta rounded-full bg-white px-4 py-2.5 text-xs font-extrabold text-[#0F2A5F] transition-transform hover:-translate-y-1 sm:px-6 sm:text-sm">Créer mon espace ↗</Link></nav>
    <div className="landing-container relative flex gap-2 overflow-x-auto border-b border-white/25 py-2 text-xs font-bold lg:hidden" aria-label="Sections de la page">{[["Pourquoi","pourquoi"],["Calculateur","calculateur"],["Fonctionnalités","fonctionnalites"],["Étapes","etapes"],["Tarifs","tarifs"]].map(([label,id])=><a key={id} className="whitespace-nowrap rounded-full px-3 py-2 hover:bg-white/15" href={`#${id}`}>{label}</a>)}</div>
    <div className="landing-container relative grid min-h-[650px] items-center gap-7 py-12 lg:grid-cols-[1.08fr_.92fr] lg:gap-12 lg:py-16"><div className="order-2 lg:order-1"><FloatingPreview/></div><div className="order-1 max-w-2xl lg:order-2"><span className="inline-flex rounded-full border border-white/70 px-4 py-2 text-xs font-bold uppercase tracking-[.15em]">Pour cafés, restaurants & commerces</span><h1 className="mt-7 font-display text-[clamp(3.8rem,7.8vw,8.2rem)] uppercase leading-[.91] tracking-tight">FAITES-LES<br/><span className="text-[#0F2A5F]">REVENIR.</span></h1><p className="mt-7 max-w-lg text-base leading-relaxed text-white/95 sm:text-lg">Transformez chaque visite en une raison de revenir. Une carte digitale claire pour vos clients, un programme simple à piloter pour vous.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/business/login" className={button}>Créer mon programme <span className="ml-4" aria-hidden>↗</span></Link><a href="#calculateur" className={contrastButton}>Estimer mon potentiel ↓</a></div><p className="mt-7 text-xs font-medium text-white/80">Un QR code. Des points. Une bonne raison de se revoir.</p></div></div>
    <div className="relative border-t border-white/25 py-3"><div className="landing-container flex flex-wrap justify-center gap-x-10 gap-y-2 text-xs font-bold uppercase tracking-[.2em] text-white/90 sm:justify-between"><span>01 · Simple à rejoindre</span><span>02 · Facile à suivre</span><span>03 · Agréable à récompenser</span></div></div>
  </section>
  <section id="pourquoi" className="landing-section bg-[#F8FAFC]"><div className="landing-container"><SectionHeading eyebrow="01 / LE DÉCLIC" description="Moins d’oubli, plus de liens. Une expérience de fidélité pensée pour votre comptoir et pour le téléphone de vos clients.">LES HABITUDES<br/><span className="text-[#2563EB]">CHANGENT.</span></SectionHeading><div className="grid gap-5 md:grid-cols-2"><div className="rounded-[1.5rem] border-2 border-[#0F2A5F] bg-white p-7 sm:p-9"><span className="inline-block rounded-full bg-[#ededeb] px-4 py-2 text-xs font-extrabold uppercase tracking-widest">Avant</span><h3 className="mt-8 font-display text-3xl uppercase">Une relation qui s’efface.</h3><ul className="mt-7 space-y-5 text-sm leading-relaxed sm:text-base">{["La carte papier se perd ou reste au fond d’un tiroir.","La progression du client n’est pas visible facilement.","Vous manquez de repères sur les visites et récompenses."].map(item=><li key={item} className="flex gap-4"><span className="font-bold text-[#2563EB]">×</span>{item}</li>)}</ul></div><div className="rounded-[1.5rem] border-2 border-[#0F2A5F] bg-[#CCFBF1] p-7 sm:p-9"><span className="inline-block rounded-full bg-[#0F2A5F] px-4 py-2 text-xs font-extrabold uppercase tracking-widest text-white">Avec Fideli</span><h3 className="mt-8 font-display text-3xl uppercase">Une raison de revenir.</h3><ul className="mt-7 space-y-5 text-sm leading-relaxed sm:text-base">{["Le QR code ouvre un parcours d’adhésion sur téléphone.","Les points et la récompense sont visibles sur la carte client.","Vous suivez votre programme depuis l’espace commerçant."].map(item=><li key={item} className="flex gap-4"><span className="font-bold text-[#2f713d]">✓</span>{item}</li>)}</ul></div></div></div></section>
  <section id="calculateur" className="landing-section bg-[#EEF4FF]"><div className="landing-container"><SectionHeading eyebrow="02 / SIMULATION LIBRE" description="Quelques curseurs pour explorer un scénario avec vos propres chiffres. Pas de promesse de rendement, juste un calcul transparent.">ET SI ON<br/><span className="text-[#2563EB]">FAISAIT LE CALCUL ?</span></SectionHeading><LandingCalculator/></div></section>
  <section id="fonctionnalites" className="landing-section bg-[#F8FAFC]"><div className="landing-container"><SectionHeading eyebrow="03 / L’ESSENTIEL" description="Des outils concrets pour lancer un programme lisible. Les fonctionnalités ci-dessous correspondent au MVP connecté fourni dans ce projet.">TOUT CE QU’IL FAUT.<br/><span className="text-[#2563EB]">RIEN DE TROP.</span></SectionHeading><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{landingFeatures.map((feature,index)=><article key={feature.title} className="rounded-[1.4rem] border-2 border-[#0F2A5F] bg-white p-6 transition-transform duration-300 hover:-translate-y-1 sm:p-7"><div className="flex items-start justify-between"><span className="grid size-14 place-items-center rounded-2xl bg-[#EEF4FF] text-3xl text-[#2563EB]" aria-hidden>{feature.icon}</span><span className="text-xs font-bold text-black/40">0{index+1}</span></div><h3 className="mt-9 font-display text-2xl uppercase leading-tight">{feature.title}</h3><p className="mt-3 text-sm leading-relaxed text-black/60">{feature.description}</p></article>)}</div><p className="mt-7 rounded-xl border border-black/15 bg-white px-5 py-4 text-sm leading-relaxed text-black/65"><strong>À venir :</strong> l’ajout Apple Wallet et Google Wallet avec des points synchronisés. Cette fonctionnalité n’est pas annoncée comme disponible dans ce MVP.</p></div></section>
  <section id="etapes" className="landing-section bg-[#CCFBF1]"><div className="landing-container"><SectionHeading eyebrow="04 / LE PARCOURS" description="De l’inscription à la récompense : trois gestes faciles à expliquer à votre équipe et à vos clients.">TROIS ÉTAPES.<br/><span className="text-[#2563EB]">ET C’EST PARTI.</span></SectionHeading><div className="grid gap-5 md:grid-cols-3">{[["01","CRÉEZ","Définissez votre commerce et votre programme dans l’espace dédié."],["02","PARTAGEZ","Affichez votre QR code. Le client rejoint le programme depuis son téléphone."],["03","RÉCOMPENSEZ","Validez ses visites, ajoutez ses points et utilisez la récompense au bon moment."]].map(([number,title,description])=><article key={number} className="rounded-[1.5rem] border-2 border-[#0F2A5F] bg-[#F8FAFC] p-7 sm:p-8"><span className="font-display text-6xl text-[#2563EB]">{number}</span><div className="mt-8 h-px bg-[#0F2A5F]/25"/><h3 className="mt-6 font-display text-3xl">{title}</h3><p className="mt-3 text-sm leading-relaxed text-black/65">{description}</p></article>)}</div></div></section>
  <section className="bg-[#0F2A5F] py-16 text-white sm:py-20"><div className="landing-container"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><Eyebrow>CHIFFRES CONFIGURABLES</Eyebrow><h2 className="mt-4 font-display text-4xl uppercase leading-none sm:text-6xl">LA FIDÉLITÉ<br/>EN CLAIR.</h2></div><p className="max-w-sm text-sm text-white/60">Exemple de fonctionnement du programme, pas des statistiques clients ni des résultats commerciaux.</p></div><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[["01","QR code par commerce"],[`${pointsPerVisit}`,"points par visite (exemple)"],[`${rewardPoints}`,"points pour une récompense (exemple)"],["03","étapes pour démarrer"]].map(([figure,label])=><div key={label} className="border-t border-white/30 pt-5"><strong className="font-display text-5xl text-[#93C5FD] sm:text-7xl">{figure}</strong><p className="mt-2 max-w-[190px] text-xs leading-relaxed text-white/65 sm:text-sm">{label}</p></div>)}</div></div></section>
  <section id="confiance" className="landing-section bg-[#F8FAFC]"><div className="landing-container"><div className="text-center"><span className="landing-eyebrow">06 / CONFIANCE</span><h2 className="landing-title mt-5">SÉCURISÉ, <span className="text-[#14B8A6]">SIMPLE.</span></h2></div><div className="mt-12 grid gap-6 md:grid-cols-3">{landingConfig.trust.map(t => <div key={t.title} className="rounded-[1.5rem] border-2 border-[#0F2A5F] bg-white p-7"><span className="text-3xl" aria-hidden>{t.icon}</span><h3 className="font-display mt-4 text-xl">{t.title}</h3><p className="mt-2 text-sm leading-relaxed text-black/65">{t.description}</p></div>)}</div><ul className="mx-auto mt-12 grid max-w-3xl gap-3 text-sm font-medium sm:grid-cols-2">{landingConfig.differentiators.map(d => <li key={d} className="flex gap-3 rounded-2xl bg-[#CCFBF1] p-4"><span className="font-bold text-[#0D9488]">✓</span>{d}</li>)}</ul></div></section>
  <section id="tarifs" className="landing-section bg-[#EEF4FF]"><div className="landing-container"><LandingPricing/></div></section>
  <section className="bg-[#2563EB] py-20 text-white sm:py-28"><div className="landing-container relative overflow-hidden"><span className="absolute right-0 top-0 hidden rotate-[-12deg] font-display text-[16rem] leading-none text-white/15 lg:block" aria-hidden>✳</span><Eyebrow>À VOUS DE JOUER</Eyebrow><h2 className="relative mt-5 font-display text-[clamp(3.8rem,8vw,8rem)] uppercase leading-[.94]">VOS CLIENTS<br/>REVIENNENT.<br/><span className="text-[#0F2A5F]">ÇA COMMENCE ICI.</span></h2><p className="relative mt-7 max-w-xl text-base leading-relaxed text-white/90">Créez votre espace, personnalisez votre programme et découvrez le parcours côté client.</p><div className="relative mt-9 flex flex-wrap gap-3"><Link href="/business/login" className={button}>Créer mon espace ↗</Link><Link href="/demo" className={contrastButton}>Explorer le parcours</Link></div></div></section>
  <footer className="bg-[#0F2A5F] py-9 text-white"><div className="landing-container flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><span className="font-display text-3xl">FIDELI✳</span><p className="text-xs text-white/55">Un outil de fidélité à construire avec vos commerces.</p><div className="flex flex-wrap gap-5 text-xs font-semibold"><a href="#accueil">Retour en haut ↑</a><Link href="/privacy">Confidentialité</Link><Link href="/business/login">Connexion</Link></div></div></footer>
</div>; }
